### ISSUE TITLE
Issue when deleting parent page

### ISSUE THREAD

**Issue by a-barbieri** [denkGroot/Spina#195] opened 2016-09-30 17:09 UTC
I was working with this page structure.

```
posts
- post A
- post B
```

I decided I didn't need `posts` and its children anymore so I deleted `posts` as first thing. The issue is that on the admin panel I cannot see `post A` and `post B`, but in my navigation menu they are still visible and accessible.

`Spina 0.10.0`
`Spina-template 0.4.0`

**Comment by Otterpocket** [comment] 2017-10-02 14:17
I can't reproduce this. 
Spina 0.12.0

**Comment by Bramjetten** [comment] 2017-10-02 14:35
Probably fixed in a previous version. Closing this.

**Closed by Bramjetten** 2017-10-02 14:35 UTC
Labels: bug, Hacktoberfest
